@startuml

component dgraph as d
component graphql as g
component "graphql-client" as gc
component mq as mq
component core as c
component generator

mq <-- c: depends
g <-- mq: depends
d <-- mq: depends
generator <-- g: depends
generator <-- d: depends

@enduml