@startuml

start

: create GraphQL.schema;
: create dgraph schema;
: create javaBean with \n @DgraphType \n @UidField \n @RelationshipField;
: create @Repository class extends SimpleDgraphRepository;
: create @Graphql class include \n @GraphQLQuery \n @GraphQLMutation;
: browser http://localhost:${port}/playground for create;
: add xxDgraph.xml;

end

@enduml